#include <bits/stdc++.h>
using namespace std;

int dayNumber(int day, int month, int year)
{
    static int t[] = {0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4};
    year -= month < 3;
    return (year + year / 4 - year / 100 + year / 400 + t[month - 1] + day) % 7;
}

string monthName(int monthNumber)
{
    string months[] = {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
    return months[monthNumber];
}

int totalDays(int monthNumber, int year)
{
    if (monthNumber == 0 || monthNumber == 2 || monthNumber == 4 || monthNumber == 6 || monthNumber == 7 || monthNumber == 9 || monthNumber == 11)
        return 31;
    else if (monthNumber == 3 || monthNumber == 5 || monthNumber == 8 || monthNumber == 10)
        return 30;
    else
    {
        if (year % 400 == 0 || (year % 4 == 0 && year % 100 != 0))
            return 29;
        else
            return 28;
    }
}

void printCalendar(int year)
{
    cout << endl
         << "        ╔════════════════════╗" << endl;
    cout << "        ║   Welcome to " << year << "  ║" << endl;
    cout << "        ╚════════════════════╝" << endl
         << endl
         << endl;

    int days;

    int current = dayNumber(1, 1, year);

    for (int i = 0; i < 12; i++)
    {
        days = totalDays(i, year);

        cout << "   ❑ ❑ ❑ ❑ ❑ ❑ ❑ ❑ ❑ " << monthName(i) << ", " << year << endl
             << endl;
        cout
            << "  Sun  Mon  Tue  Wed  Thu  Fri  Sat" << endl
            << endl;

        int k;
        for (k = 0; k < current; k++)
            cout << setw(5) << " ";

        for (int j = 1; j <= days; j++)
        {
            cout << setw(5) << j;

            if (++k > 6)
            {
                k = 0;
                cout << endl
                     << endl;
            }
        }

        if (k)
            cout << endl
                 << endl;

        current = k;
    }
}

void saveFile(int year)
{
    char ch;
    cout << "Do you want to save the calendar as a .txt file? (Type 'Y' or 'y' for Yes): ";
    cin >> ch;
    cout << endl;

    if (ch == 'Y' || ch == 'y')
    {
        ofstream outputFile("calendar_" + to_string(year) + ".txt");

        outputFile << endl
                   << "        ╔ ═ ═ ═ ═ ═ ═ ═ ═ ╗" << endl;
        outputFile << "        ║ Welcome to " << year << " ║" << endl;
        outputFile << "        ╚ ═ ═ ═ ═ ═ ═ ═ ═ ╝" << endl
                   << endl;

        int days;
        int current = dayNumber(1, 1, year);

        for (int i = 0; i < 12; i++)
        {
            days = totalDays(i, year);
            outputFile << "  ❑ ❑ ❑ ❑ ❑ ❑ ❑ ❑ ❑ " << monthName(i) << ", " << year << endl
                       << endl;
            outputFile << "  Sun  Mon  Tue  Wed  Thu  Fri  Sat" << endl
                       << endl;

            int k;
            for (k = 0; k < current; k++)
                outputFile << setw(5) << " ";

            for (int j = 1; j <= days; j++)
            {
                outputFile << setw(5) << j;

                if (++k > 6)
                {
                    k = 0;
                    outputFile << endl
                               << endl;
                }
            }

            if (k)
                outputFile << endl
                           << endl;

            current = k;
        }

        outputFile << "// Generated by : Calender Generator" << endl
                   << "// Credit : @mdnrkn -> https://github.com/mdnrkn";

        cout << endl
             << "Calendar saved as 'calendar_" << year << ".txt' in your device storage," << endl
             << "Thanks for using Calendar Generator!" << endl;
    }
    else
    {
        cout << "Thanks for using Calendar Generator!" << endl;
    }
}

int main()
{
    int year;
    cout << "Enter the year : ";
    cin >> year;
    cout << endl
         << endl;

    printCalendar(year);
    saveFile(year);

    return 0;
}